### ISSUE TITLE
Generating files without extension

### ISSUE THREAD

**Issue by ujovlado** [jekyll/jekyll-redirect-from#95] opened 2016-01-28 15:28 UTC
With `jekyll v3.1.0` this plugin generates files without ".html" suffix.

With `jekyll v3.0.0` it works.

**Comment by ujovlado** [comment] 2016-01-28 15:35
Steps to reproduce:
```bash
jekyll -v
# jekyll 3.0.0
jekyll b
# your files with html extension
gem install jekyll -v 3.1.0
jekyll -v
# jekyll 3.1.0
jekyll b
# your files without html extension
```

**Comment by parkr** [comment] 2016-01-28 22:35
This is a duplicate of https://github.com/jekyll/jekyll/issues/4397

```irb
>> File.extname("/redirect-from/me/")
=> ""
```

**Closed by parkr** 2016-01-28 22:35 UTC
